server:
  port: 8081

spring:
  application:
    name: cctv
  config:
    import: file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.helios.cctv.dto

