server:
  port: 8081
  tomcat:
    relaxed-query-chars: '[,]'
    relaxed-path-chars: '[,]'

spring:
  application:
    name: cctv
  config:
    import: file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  jpa:
    properties:
      hibernate.jdbc.batch_size: 500
      hibernate.order_inserts: true
      hibernate.order_updates: true

  data:
    redis:
      host: ${REDIS_URL}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  redis:
    redisson:
      config: |
        singleServerConfig:
          address: "redis://${spring.data.redis.host}:${spring.data.redis.port}"
          password: "${spring.data.redis.password}"
          connectTimeout: 3000
          timeout: 5000
          retryAttempts: 1
          retryInterval: 1000
          pingConnectionInterval: 30000
          keepAlive: true
          tcpNoDelay: true



mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.helios.cctv.dto
  type-handlers-package: com.helios.cctv.config

logging:
  level:
    root: info
    org.mybatis: debug         # MyBatis 실행 쿼리 로그
    jdbc.sqlonly: debug
    jdbc.resultset: debug
    org.springframework.jdbc: debug
    org.springframework.transaction: debug
    com.zaxxer.hikari: debug   # DB 연결 문제 추적

cctv:
  capture:
    output-dir: "C:\\helios-CCTV\\capture\\2"
    width: 1920
    height: 1080
    seconds-to-capture: 20   # 총 20초 읽기
    fps: 1                   # 초당 1장 => 총 20장
    ffmpeg-path: "C:\\helios-CCTV\\ffmpeg-7.1.1-essentials_build\\bin\\ffmpeg.exe"    # PATH에 있으면 'ffmpeg', 아니면 "C:/ffmpeg/bin/ffmpeg.exe" 식 절대경로
    max-parallel: 4
